name: Aggiorna Playlist

on:
  schedule:
    - cron: "0 3 * * *"   # ogni giorno alle 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clona il repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installa dipendenze
        run: pip install requests

      - name: Esegui script aggiornamento
        run: python update_playlist.py

      - name: Commit e push modifiche
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ita.m3u
          git commit -m "Aggiornamento automatico playlist"
          git push